### ISSUE TITLE
Vertical alignment support for nested context menu items

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-context-menu#218]
If a sub-menu is opened near the bottom of the viewport, the menu should open upwards and be bottom aligned

**Comment by yuriy-fix** [comment]
**Note:** the logic for alignment is already there https://github.com/vaadin/vaadin-context-menu/blob/master/src/vaadin-context-menu.html#L572 and the thing that should be updated is [y](https://github.com/vaadin/vaadin-context-menu/blob/master/src/vaadin-contextmenu-items-mixin.html#L151) to be the `bottom` of the item instead of `top` in case it should be opened upwards.
