### ISSUE TITLE
Menu focus lost when nested sub-menu closed on other item hover

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-context-menu#230]
From https://github.com/vaadin/vaadin-menu-bar/pull/24#pullrequestreview-221541779

1. open context-menu
2. hover on a parent item in that context-menu to open a nested sub-menu
3. hover on a non-parent item on the first context-menu

As the nested sub-menu closes, the focus on the main context-menu is lost.

**Comment by pekam** [comment]
It is actually not clear to me what is the expected behavior.

In the [w3 menubar example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-1/menubar-1.html), there is no focus at all when you navigate with mouse. If you navigate first with keyboard to get the focus, and then hover on a non-parent item (which is a weird behavior to switch from keyboard to mouse like that), then the sub-menu is not closed at all and focus is not moved. If you use only your mouse (so there's no focus at all), the sub-menu is closed as soon as the mouse leaves the sub-menu overlay, which is totally different from our context-menu behavior.

So I have at least three options for this:
1. Focus the non-parent item which was the target of the `mouseover` event
2. Focus the parent-item whose sub-menu was closed
3. Don't close the sub-menu at all and don't move focus

Each of these feel a bit weird in their own way.

**Comment by pekam** [comment]
We have decided to go with option 2. Focus the parent-item whose sub-menu was closed
