### ISSUE TITLE
Contextmenu does not respect right click coordinates

### ISSUE THREAD

**Issue by Mika83AC** [vaadin/vaadin-context-menu#45]
Assuming this is a webcomponent template using the vaadin-context-menu:

```
<template>
	<div id="container"></div>

	<vaadin-context-menu id="contextmenu">
		<template>
			<paper-menu on-iron-select="_onContextMenuClick">
				<paper-item id="new">New</paper-item>
			</paper-menu>
		</template>
	</vaadin-context-menu>
</template>
```

When adding elements to the div "container" and adding a listener to the "mousedown" event by:

```
var currentElement = document.createElement('span');
currentElement.innerHTML = "test";
Polymer.dom(this.$.container).appendChild(currentElement);

this.listen(currentElement, 'mousedown', '_nodeText_onMouseDown');
```

```
_nodeText_onMouseDown: function(e, detail) {
        if(e.button === 2) {
	     this.$.contextmenu.open(e);
	}
}

```
the position of the content menu is not the position the mouse right click was executed.

**Comment by platosha** [comment]
@Mika83AC hello! I’ve tried to reproduce your use case, it works so far: http://jsbin.com/lulexenati/edit?html,output

In which browsers you have this issue?

Also, just out of curiosity: do you have any special reasons for manual opening with `open` method in the right click listener instead of just wrapping your container with `<vaadin-context-menu>` or setting the container as a listener element (e. g., `this.$.contextmenu.listenOn = this.$.container;`)?

**Comment by Mika83AC** [comment]
@platosha Thx for your reply.

Your example isn't working for me. It throws an error when making a right click on the text.

 I'm using the latest Chrome 55.

And I'm performing the open manually because i don't know how to do it otherwise ;) I'm building a tree view component and only when the user clicks on a node text of the tree view the context menu should open. If he clicks on the expand/collapse icons or an empty space, no context menu should be displayed. So i thought it would be the easiest way to at mousedown listener for each node text.

Simplified the DOM of my tree will look like:

```
<div id="container">
		<div id="node1">
			<iron-icon></iron-icon>
			<span>node1</span>
			<div id="node1_childs">
				<div id="node1_1">
					<iron-icon></iron-icon>
					<span>node1_1</span>
				</div>
				<div id="node1_2">
					<iron-icon></iron-icon>
					<span>node1_2</span>
					<div id="node1_2_childs">
						....
					</div>
				</div>
			</div>
		</div>
	</div>
```

**Comment by limonte** [comment]
Confirming that http://jsbin.com/lulexenati/edit?html,output isn't working in Chrome/Linux, it throws:

```
vaadin-context-menu.html:164 Uncaught TypeError: Polymer.dom(...).children.filter is not a function
    at HTMLElement._openedChanged (vaadin-context-menu.html:164)
    at runMethodEffect (property-effects.html:671)
    at Object.runMethodObserverEffect [as fn] (property-effects.html:168)
    at runEffectsForProperty (batched-effects.html:135)
    at runEffects (batched-effects.html:117)
    at HTMLElement._propertiesChanged (batched-effects.html:179)
    at HTMLElement._flushProperties (property-accessors.html:205)
    at HTMLElement._flushProperties (property-effects.html:1205)
    at HTMLElement._invalidateProperties (property-effects.html:1173)
    at HTMLElement._setProperty (property-accessors.html:134)
```

**Comment by limonte** [comment]
The actual reason of http://jsbin.com/lulexenati/edit?html,output not working is https://twitter.com/polymer/status/808351947216461824

polygit serves 2.0-preview version of Polymer: http://jsbin.com/wizivaceni/edit?html,console,output

**Comment by platosha** [comment]
@Mika83AC this suggests that our documentation didn’t work for explaining it. Fortunately, the documentation improvement is in progress currently, it is coming soon in the next release.

Basically, you can wrap the entire tree inside the context menu and then refine the set of descendant elements targeted with a context menu using the `selector` property. Based on your quote, I would do:

```javascript
<vaadin-context-menu selector="span">
  <template>
    <paper-menu>
      <paper-item>New</paper-item>
    </paper-menu>
  </template>

  <div id="container">
    <div id="node1">
	<iron-icon></iron-icon>
	<span>node1</span>
        ...
    </div>
  </div>
</vaadin-context-menu>
```

This should “assign” the context menu in the template for all the `span` descendants, i. e., matching the selector of the `selector` property. You can use also use other kinds of selectors if necessary, such as `.class`, `[attribute]` and so on.

The menu is opened by default after both the `contextmenu` events, which are triggered by right click on mouse environments, and the long touch press events on touch devices. You don’t have to setup the event listener manually in this case, the events will naturally bubble from your content to the parent `<vaadin-context-menu>`, which listens for the events on itself by default.

If wrapping the content is not applicable for you, you can also set the `listenOn` property in order to use any element as a listener for the context menu opening events. Once again, all the content inside this element will trigger the context menu by default, an the `selector` property could be used the same way filtering the target set of elements inside the listener element.

**Comment by Mika83AC** [comment]
@platosha Yes, the docs have been a little unclear for me about how to implement the context menu ;)

Now following your last suggestion here, everything works fine! Wrapping my container and using span as selector wasn't a problem. Just didn't know i simply had to do that.

But maybe in the open() method you can fallback to the native event x/y coordinate extraction if the polymer event try has failed (what was the case in my experiments). Than the open() method would be most flexible for all use cases.

Thx for your help! :+1:

**Comment by Mika83AC** [comment]
Hm... there arose another question:

If I wrap the container div with the context-menu and set the selector to span, how can I prevent the default browser context menu from opening if the user clicks on a any other area of the container div which is not a span (and so is not covered by your context-menu functionalities)? As i'm building a treeview, there is plenty space to click inside the container div where there is not a span. ;)

**Comment by platosha** [comment]
In order to stop the default browser context menu from opening, prevent the default action for `contextmenu` events:
```html
<div id="conainer" on-contextmenu="_preventDefault">...</div>
```
```javascript
_preventDefault: function(e) {
  e.preventDefault();
}
```

**Comment by Mika83AC** [comment]
Ahrg... I tried at least 5 different variants of using the e.PreventDefault(), but not this one ... and this one is the one which is working ...

Sorry :)

**Comment by Saulis** [comment]
@Mika83AC are your problems resolved? Is it ok to close this ticket?

**Comment by Mika83AC** [comment]
Yes, everything is fine now. Thx.
